export const USER_TYPING = 'USER_TYPING';
export const USER_STOPPED_TYPING = 'USER_STOPPED_TYPING';
export const USER_JOINED_CHAT = 'USER_JOINED_CHAT';
export const NEW_MESSAGE_ADDED = 'NEW_MESSAGE_ADDED';
export const USER_LEFT_CHAT = 'USER_LEFT_CHAT';
export const MESSAGES_LOADED = 'MESSAGES_LOADED';

export default {};
